### ISSUE TITLE
Strings and letters radio buttons for randomTextColor.js

### ISSUE THREAD

**Issue by gchegr** [sky-chaser-high/adobe-illustrator-scripts#1]
I assume some might want to have to color text not by words, but by strings or sentences or letters. Perhaps even a delimiter mode can be used, where not only a dot-period can be used to track ends of sentences.

**Comment by sky-chaser-high** [comment]
Hi, gchegr .
Thanks for the feedback.
Nice idea.
I will try to respond as soon as possible.

**Comment by sky-chaser-high** [comment]
Added the function to change colors by character or sentences.
