### ISSUE TITLE
Highlightword.js with styles and swatches?!

### ISSUE THREAD

**Issue by 1tszabi** [sky-chaser-high/adobe-illustrator-scripts#10]
Can you write a highlightword script in which you can choose from predefined character styles and swatches (cmyk, pantone, etc.)? Thank you!

![image](https://github.com/user-attachments/assets/ed62fe7a-5d69-4900-a2cb-a906ead62d53)

**Comment by sky-chaser-high** [comment]
Hi 1tszabi
Thanks for the suggestion.
I'll add those two features to highlightWord.js. However, it will take a little time to update.

**Comment by 1tszabi** [comment]
Okay, i see!
Thansk for your response!

**Comment by sky-chaser-high** [comment]
Added the functions to apply swatches, character and paragraph styles.
