### ISSUE TITLE
Local links at the start of the page don’t work

### ISSUE THREAD

**Issue by gchegr** [sky-chaser-high/adobe-illustrator-scripts#2]
Dots are missing in the links. Compare them with the actual local anchors next to headers.
Other than that — a nice collection, some really rare but sharp tools. Good job!

**Comment by gchegr** [comment]
`https://github.com/sky-chaser-high/adobe-illustrator-scripts#showArtboardName.js` — does not work
`https://github.com/sky-chaser-high/adobe-illustrator-scripts#showArtboardNamejs` — does work

**Comment by sky-chaser-high** [comment]
Hi gchegr.
Thank you.
I have modified the README.
I didn't notice it because it was working in my local environment.
I see that if the link has an extension, it will not jump. I did not know that.
