### ISSUE TITLE
The resetToFullScale，How to maintain the rotation angle of the object

### ISSUE THREAD

**Issue by jxyun99** [sky-chaser-high/adobe-illustrator-scripts#4]
resetToFullScale.js
if I want to maintain the rotation angle of the object，What should I do?

**Comment by sky-chaser-high** [comment]
Hi jxyun99.

The angle is recorded in Tag.
It would be an easy way to get the value from there and then restore the angle.

For example:
```javascript
var item = app.activeDocument.selection[0];
var tag = item.tags[0];
var value = tag.value;

// convert radian to degree
var deg = 180 / Math.PI * value;

resetToFullScale(item);

// restore the angle
item.rotate(deg);
```

**Comment by jxyun99** [comment]
[https://github.com/jxyun99/test/blob/main/test.gif](url)

I seem to have found a bug. If an object is rotated by an angle, such as -180°, the position after resizing will not be the original position

https://github.com/jxyun99/test/blob/main/test.gif is Presentation Diagram

**Comment by sky-chaser-high** [comment]
I have confirmed the bug here as well.
I'll fix it.

**Comment by sky-chaser-high** [comment]
Fixed a bug.

**Comment by jxyun99** [comment]
Thank you. I just tested it is ok
