### ISSUE TITLE
createColorChart.js ignores selected color space

### ISSUE THREAD

**Issue by izumitelj** [sky-chaser-high/adobe-illustrator-scripts#5]
I'm experiencing problem with this script. The color space selected with the main radio button is ignored and the document is created in default (new-file) space. It's possible to still use the script by setting new default and closing/opening illustrator, but it's looks like a bug. Thanks.

Experienced on AI CC 2020 v24 x64, Win 10 x64.

**Comment by sky-chaser-high** [comment]
Hi izumitelj.
Thanks for the bug report. I was able to confirm it here as well.
I'll fix it.

**Comment by sky-chaser-high** [comment]
Fixed a bug.

**Comment by izumitelj** [comment]
Hi sky-chaser, thanx for the fix! 
I can confirm that it resolved this bug 🚀
