### ISSUE TITLE
justifyContentSpaceBetween.js works wrong, if a text is already has custom tracking

### ISSUE THREAD

**Issue by gchegr** [sky-chaser-high/adobe-illustrator-scripts#6]
Try to select a point type text with some tracking already applied and a larger line together, run the script.
The result does not match the line’s length.
It looks like the script does not reset tracking before measuring the width of it.

**Comment by sky-chaser-high** [comment]
Hi gchegr.
It does not compare the number of characters and align to the one with more characters.
It compares the current width including tracking and aligns to the longer text.

**Comment by gchegr** [comment]
Perhaps I phrased it wrong. Here is a demo.
![justify_test](https://github.com/sky-chaser-high/adobe-illustrator-scripts/assets/81404846/027701cb-6418-4fbb-96b1-cd5acc8379f9)
As you can see, if I try to adjust tracking with the script for the text that already had it modified, the result is way off.

**Comment by creold** [comment]
If you run the script again on the same point text, you would expect the size to match again. This would be predictable to the user.
![2023-10-27 10 13 28](https://github.com/sky-chaser-high/adobe-illustrator-scripts/assets/32217031/5b6dc17b-81ab-4f10-a1e9-74ffe10c418e)

**Comment by sky-chaser-high** [comment]
I guess I was mistaken. My apologies.
I was able to confirm it here as well.
I'll fix it.

**Comment by sky-chaser-high** [comment]
Upon investigation, it appears that the behavior is incorrect when kerning is set to Auto.
I didn't notice it in the Japanese version because it worked in Auto.
Modified to set kerning to 0.

**Comment by creold** [comment]
I think it works well right now.

**Comment by gchegr** [comment]
Confirm it is fixed.
