### ISSUE TITLE
"addAnchorPoints.js" Pressing Enter to confirm triggers Illustrator's Enter function at the same time

### ISSUE THREAD

**Issue by hzinchengdu** [sky-chaser-high/adobe-illustrator-scripts#8]
[https://github.com/sky-chaser-high/adobe-illustrator-scripts?tab=readme-ov-file#addanchorpointsjs](https://github.com/sky-chaser-high/adobe-illustrator-scripts?tab=readme-ov-file#addanchorpointsjs)

In Windows, pressing Enter to confirm triggers Illustrator's Enter function at the same time, so hopefully this will solve the problem.

Also I need to realize that only an anchor point is added when clicked and no window pops up, how do I change the code.

![Enter](https://github.com/sky-chaser-high/adobe-illustrator-scripts/assets/126546789/dc478415-5f1e-4bd0-86cb-31acd680807d)

**Comment by sky-chaser-high** [comment]
Hi, hzinchengdu
Sorry, I don’t currently own Windows and cannot confirm the problem.
Please respond by clicking the OK button instead of the Enter key.
