### ISSUE TITLE
The relinkFileExtensionExtra.js Can I replace the PDF page?

### ISSUE THREAD

**Issue by jxyun99** [sky-chaser-high/adobe-illustrator-scripts#9]
For example, if all the linked files are in PDF format and the current link is page 1 of PDF, I would like to use a script to batch link different PDFs into page 2
![pdfa](https://github.com/user-attachments/assets/2e4f7a62-c32c-4529-85dc-4c30978693e7)
![pdfb](https://github.com/user-attachments/assets/4408d179-76ed-46dd-9828-b4b007629e1b)
![33](https://github.com/user-attachments/assets/df3c25db-8ab2-4896-869d-9f3e878c20bd)

**Comment by sky-chaser-high** [comment]
Hi jxyun99
It doesn't seem possible to specify a page in the relink, but with some ingenuity, it might be possible to implement it.
I'll give it a try.

**Comment by jxyun99** [comment]
[placeReOptionAI.zip](https://github.com/user-attachments/files/16490022/placeReOptionAI.zip)
I recently found a script that can replace pages with PDF links, but it can only replace one file at a time and does not support CS6. Can you see if it has any reference value?

**Comment by sky-chaser-high** [comment]
Now, we are upgrading relinkFileExtensionExtra.js and will have it finished by the end of this week.
If you want placeReOptionAI.jsx to work in CS6, change the 16 in line 23 to 15. I don't have CS6, I can't verify this, but it may not work with the change.
I think it would be better to wait for the relinkFileExtensionExtra.js modification as it would require significant modification to modify it to replace multiple files at the same time.

**Comment by sky-chaser-high** [comment]
Hi jxyun99
Updated. Please try it out.

**Comment by jxyun99** [comment]
Tested in AI 2024, it works normally, but not in CS6
I also found a bug where if the linked PDF object rotates, the newly linked file will not rotate along with it

**Comment by sky-chaser-high** [comment]
CS6 and CC do not seem to allow pages to be specified.
CC2015 and later were able to specify.
It looks like we will have to give up on the pre CC versions.
I will correct it regarding rotation.

**Comment by jxyun99** [comment]
I have found another script that can replace the specified PDF page for CS6（
The script specifies page 2）, to see if it has any reference value 
[Placed.zip](https://github.com/user-attachments/files/16736046/Placed.zip)

**Comment by sky-chaser-high** [comment]
Updated.

**Comment by jxyun99** [comment]
Thank you, the test is done
